# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-30 21:05
from __future__ import unicode_literals

import community.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=models.SET(community.models.get_sentinel_user), related_name='village_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentneed',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.Requirement'),
        ),
        migrations.AddField(
            model_name='studentneed',
            name='sponsers',
            field=models.ManyToManyField(through='support.Support', to='support.Sponser'),
        ),
        migrations.AddField(
            model_name='studentneed',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.Student'),
        ),
        migrations.AddField(
            model_name='studentimage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='requirements',
            field=models.ManyToManyField(blank=True, through='community.StudentNeed', to='community.Requirement'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='community.School'),
        ),
        migrations.AddField(
            model_name='student',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='community.Village'),
        ),
        migrations.AddField(
            model_name='school',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=models.SET(community.models.get_sentinel_user), related_name='school_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='community.Village'),
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together=set([('name', 'district')]),
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together=set([('name', 'village')]),
        ),
    ]
